#!/bin/bash

dir="$(dirname "$0")"

# CONFIG
function config {
echo ""
show_question 'What would you like to do? '
echo ""
echo "1. Configure Dock settings?"
echo "2. Configure Finder settings?"
echo "3. Configure Terminal settings?"
echo "4. Configure default location for screenshots?"
echo "5. Configure other settings?"
echo "r. Return"
echo ""
show_question 'Enter your choice:' && read REPLY
case $REPLY in
# Dock
1) echo "" && dock;;
# Finder
2) echo "" && finder;;
# Terminal
3) echo "" && terminal;;
# Screenshots
4) echo "" && screenshots;;
# Defaults
5) echo "" && misc;;
# Return
[Rr]*) clear && main;;
# Invalid choice
* ) clear && show_error '\aNot an option, try again.' && config;;
esac
}