#!/bin/bash

dir="$(dirname "$0")"

# CONFIG
function config {
echo ""
show_question 'What would you like to do? '
echo ""
echo "1. Configure Dock settings?"
echo "2. Configure Finder settings?"
echo "3. Configure Terminal settings?"
echo "4. Set screenshot location?"
echo "5. Configure default settings?"
echo "r. Return"
echo ""
show_question 'Enter your choice:' && read REPLY
case $REPLY in
# Dock
1) echo "" && dock;;
# Finder
2) echo "" && finder;;
# Terminal
3) echo "" && terminal;;
# Screenshots
4) echo "" && screenshots;;
# Defaults
5)  
    show_info 'Configuring default settings...'
    # DS Store
    echo "Disabling the creation of '.DS_Store' files on network drives..."
    defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
    bold 'Done.'
    # Font Smoothing
    echo "Configuring Font Smoothing..."
    defaults write -g AppleFontSmoothing -int 0
    bold 'Done.'
    show_info 'You may need to log out for some changes to take effect.'
    # Done 
    show_success 'Done.' && config
    ;;
# Return
[Rr]*) clear && main;;
# Invalid choice
* ) clear && show_error '\aNot an option, try again.' && config;;
esac
}