#!/bin/bash

dir="$(dirname "$0")"

# THIRD PARTY APPLICATIONS
function install {
show_question 'What would you like to install? '
echo ''
echo '1. Xcode Command Line Tools?'
echo '2. Homebrew?'
echo '3. Ruby Version Manager (RVM)?'
echo 'r. Return'
echo ''
show_info 'Enter your choice:' && read REPLY
case $REPLY in
# Install Xcode Command Line Tools
1) 
    show_question 'Install Xcode Command Line Tools? (Y)es, (N)o :'
    echo ''
    show_error 'Choosing (Y)es will exit this script.'
    echo ''
    read REPLY
    case $REPLY in
    # Positive action
    [Yy]* ) 
        echo 'Installing...'
        xcode-select --install
        echo 'Moving on...'
        install
        ;;
    # Negative action
    [Nn]* )
        clear && install;;
    # Error
    * )
        clear && show_error '\aSorry, try again.' 
        install
        ;;
    esac
    ;;
# Homebrew
2)
    echo 'Installing Homebrew...'
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    show_success 'Done.'
    install
    ;;
# RVM
3)
    echo 'Installing RVM...'
    \curl -sSL https://get.rvm.io | bash -s stable --ruby
    source /Users/Sam/.rvm/scripts/rvm
    show_success 'Done.'
    install
    ;;
# Return
[Rr]*) 
    clear && main;;
# Invalid choice
* ) 
    clear && show_error '\aNot an option, try again.' && install;;
esac
}